"""Module extensions for tools_claude (bzlmod)."""

load("//claude/private:repo.bzl", "claude_toolchains")

_OS_TO_CONSTRAINT = {
    "darwin": "@platforms//os:macos",
    "linux": "@platforms//os:linux",
}

_ARCH_TO_CONSTRAINT = {
    "amd64": "@platforms//cpu:x86_64",
    "arm64": "@platforms//cpu:aarch64",
}

_PLATFORMS = ["darwin_arm64", "darwin_amd64", "linux_arm64", "linux_amd64"]

_TOOLCHAIN_BUILD_HEADER = """# Generated by tools_claude

load("@tools_claude//claude/private:toolchain.bzl", "claude_toolchain")

package(default_visibility = ["//visibility:public"])
"""

_TOOLCHAIN_BUILD_TEMPLATE = """
claude_toolchain(
    name = "{platform}_impl",
    claude = "@claude_{platform}//:claude",
)

toolchain(
    name = "{platform}",
    exec_compatible_with = [
        {exec_constraints},
    ],
    toolchain = ":{platform}_impl",
    toolchain_type = "@tools_claude//claude:toolchain_type",
)

toolchain(
    name = "{platform}_runtime",
    target_compatible_with = [
        {exec_constraints},
    ],
    toolchain = ":{platform}_impl",
    toolchain_type = "@tools_claude//claude:runtime_toolchain_type",
)
"""

def _claude_toolchains_repo_impl(repository_ctx):
    """Creates a repository with toolchain definitions for all platforms."""
    lines = [_TOOLCHAIN_BUILD_HEADER]

    for platform in _PLATFORMS:
        os_name, arch = platform.split("_")
        exec_constraints = [
            _OS_TO_CONSTRAINT[os_name],
            _ARCH_TO_CONSTRAINT[arch],
        ]
        exec_constraints_str = ",\n        ".join(['"{}"'.format(c) for c in exec_constraints])

        lines.append(_TOOLCHAIN_BUILD_TEMPLATE.format(
            platform = platform,
            exec_constraints = exec_constraints_str,
        ))

    repository_ctx.file("BUILD.bazel", content = "\n".join(lines))

_claude_toolchains_repo = repository_rule(
    implementation = _claude_toolchains_repo_impl,
)

def _find_modules(module_ctx):
    """Find the root module and tools_claude module.

    Toolchain configuration is only allowed in the root module, or in
    tools_claude.
    See https://github.com/bazelbuild/bazel/discussions/22024 for discussion.
    """
    root = None
    tools_claude = None
    for mod in module_ctx.modules:
        if mod.is_root:
            root = mod
        if mod.name == "tools_claude":
            tools_claude = mod
    if root == None:
        root = tools_claude
    if tools_claude == None:
        fail("Unable to find tools_claude module")
    return root, tools_claude

def _claude_impl(module_ctx):
    """Implementation of the claude module extension."""
    root, tools_claude = _find_modules(module_ctx)

    downloads = root.tags.download or tools_claude.tags.download
    download = downloads[0] if downloads else None
    version = download.version if download else ""
    sha256 = download.sha256 if download else {}
    use_latest = download.use_latest if download else False

    # Download the Claude CLI binary for each platform
    for platform in _PLATFORMS:
        claude_toolchains(
            name = "claude_" + platform,
            version = version,
            platform = platform,
            sha256 = sha256.get(platform, ""),
            use_latest = use_latest,
        )

    # Create the toolchains repository
    _claude_toolchains_repo(name = "claude_toolchains")

_download = tag_class(
    attrs = {
        "version": attr.string(
            doc = "Version to download. If empty, uses default version.",
        ),
        "sha256": attr.string_dict(
            doc = "SHA256 hashes per platform (e.g., {'darwin_arm64': 'abc...', 'linux_amd64': 'def...'}).",
        ),
        "use_latest": attr.bool(
            default = False,
            doc = "If true, fetches the latest version instead of the default.",
        ),
    },
)

claude = module_extension(
    implementation = _claude_impl,
    tag_classes = {
        "download": _download,
    },
)
